
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/recipes_api
    username: recipes_app
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

